config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do 
    get 'users/search' => 'registrations#search'
    get 'users/:id' => 'registrations#show', :as => :user
  end

  root 'items#index'
  delete 'items/delete/:id', to: 'items#destroy', as: :delete_item
  delete 'claims/:id', to: 'claims#destroy', as: :delete_claim
  resources :items
  resources :messages
  resources :relationships, only: [:create, :destroy]

end

app/models/claim.rb
class Claim < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	belongs_to :claimer, :class_name => "User"
	has_one :claim
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, :class_name => 'User'
	belongs_to :followed, :class_name => 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

	has_many :items
  has_many :claims, foreign_key: "claimer_id", dependent: :destroy, :class_name => "Item"
  has_many :claimed_items, :through => :claims, :source => :user, :class_name => "Item"
	has_many :followed_relationships, foreign_key: "follower_id", dependent: :destroy, :class_name => "Relationship"

  has_many :followed_users, :through => :followed_relationships, :source => :followed, :class_name => "User"

  has_many :follower_relationships, foreign_key: "followed_id", dependent: :destroy, :class_name => "Relationship"
  has_many :followers, :through => :follower_relationships, :source => :follower, :class_name => "User"

  def self.search(query)
    self.where("user_name LIKE :query OR first_name LIKE :query OR last_name LIKE :query OR email LIKE :query", query: "%#{query}%")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController

	def destroy
    	@claim = Claim.find[:id]
    	@claim.destroy
    	redirect_to items_path
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = current_user.items
		if params[:search]
			@users = User.search(params[:search])
		end
	end

	def show
		@item = Item.find(params[:id])
	end

	def new
		@item = Item.new
	end

	def edit
		@item = Item.find(params[:id])
	end

	def create
		@item = current_user.items.build create_params
		
		if @item.save
			redirect_to item_path(@item)
		else
			render 'new'
		end
	end

	def update
		@item = Item.find(params[:id])
		if @item.user == current_user
			@item.update(create_params)
		else
			@item.update(claim_params)
		end

		if @item.save
    		redirect_to item_path(@item)
    	else
    		flash.now[:error] = @item.errors.messages.first.join(" ")
    		render 'edit'
    	end
	end

	def destroy
    	@item = Item.find(params[:id])
    	@item.destroy
    	redirect_to items_path
	end

	private

	def create_params
		params.require(:item).permit(:title, :price, :photo, :description, :link, :claimed_by, :claimed => 'false')
	end

	def claim_params
		params.require(:item).permit(:claimed, :claimer_id)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def index
	end

	def new
	end

	def create
	end

	def show
	end

	def destroy
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def search
		@users = User.search(params[:search])
	end

	def show
		@user = User.find(params[:id])
    @items = @user.items
	end

  private

  def sign_up_params
    params.require(:user).permit(:user_name, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:user_name, :first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		@relationship = Relationship.find_or_initialize_by followed_id: params[:followed_id], follower_id: current_user.id
		if @relationship.save

			redirect_to items_path
		else
			render 'registrations/search_results'
		end
	end

	def destroy
		@relationship = Relationship.find_by(follower_id: current_user, followed_id: params[:id])
		@relationship.destroy
		if @relationship.destroy
			redirect_to items_path
		else
			render 'registrations/show'
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	skip_before_action :authenticate_user!

	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/claims/show.html.erb
<h1><%= claims.each do |claim| %>
<%= "#{claim} #{claim.claimer_id} #{claim.item_id}" %>
<% end %>

app/views/items/_claim.html.erb
<%= "Item already claimed for #{@item.user.user_name}." %> 
<% if current_user.id == @item.claimer_id %>
    <%= form_for @item do |f| %>
    	<%= f.hidden_field(:item_id, value: @item.id) %>
    	<%= f.hidden_field(:claimer_id, value: current_user.id) %>
    	<%= submit_tag "UnClaim Item", @item, :method => :delete %><br> 
    <% end %>
<% end %>

app/views/items/_form.html.erb
<%= flash[:error] %>
  <%=  form_for @item do |f| %>
    <fieldset>
      <div>
        <%=  f.label :title %>
        <%=  f.text_field :title %>
      </div>
      <div>
        <%=  f.label :price %>
        <%=  f.text_field :price %>
      </div>
      <div>
        <%=  f.label :description %>
        <%=  f.text_field :description %>
      </div>
      <div>
        <%=  f.label :photo %>
        <%=  f.text_field :photo %>
      </div>
      <div>
        <%=  f.label :link %>
        <%=  f.text_field :link %>
      </div>
    </fieldset>
<%= f.submit @item.new_record? ? "Create" : "Update" %>
<%= link_to "Cancel", items_path %>
<%= link_to 'Back to List', items_path %>
<% end %>

app/views/items/edit.html.erb
<% if @item.user == current_user %>
<h1>Edit Item</h1>
	<%= render 'form' %>
	<% else %>
	<h2>Claim Item</h2>
		<%= render 'claim' %>
	<% end %>

app/views/items/index.html.erb
<table>
	<tr>
		<td><h3>Your current wish list:</h3></td>
		<td><h3>Friends you are following:</h3></td>
		<td><h3>Claimed items:</h3></td>
	</tr>
	<tr>
		<td>
			<table>
				<% @items.each do |item| %>
  				<tr>
    				<td><%= link_to "#{item.title}", item_path(item) %></td>
    				<td><%= item.price %></td>
  				</tr>
  				<% end %>
			</table>

			<br>
			<%= link_to "Add Item", new_item_path %>
		</td>
		<td>
			<table>
			<% current_user.followed_users.each do |user| %>
  				<tr>
    				<td><%= link_to "#{user.user_name}", user_path(user) %><sp></td>
  				</tr>
  			<% end %>
  			</table>
  		</td>
  		<td>
			<table>
  			<td><% current_user.claims.each do |claim| %></td>
  			<tr>
  				<td><%= "#{claim.id}" %></td>
  				<td><%= link_to "Delete", delete_claim_path(claim.id) %></td>
  			</tr>
  			<% end %>
  			</table>
  		</td>
  	</tr	
</table>

app/views/items/new.html.erb
<h1>Add Item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<table>
    <td><h1><%= @item.title %></h1></td>
    <td><%= @item.price %></td>
  </tr>
  <tr>
    <td><%= image_tag(@item.photo) %></td>
    <td><%= @item.description %></td>
  </tr>
  <tr>
    <td><%= link_to "#{@item.link}", @item.link %></td>
  </tr>
</table>
<br>
  <%= link_to 'Home', items_path %><br>
<% if @item.user == current_user %>
  <%= link_to "Edit item", edit_item_path(@item) %><br>
  <%= link_to "Remove Item", @item, :method => :delete %><br>
<% else %>
  <%= link_to "Friend's List", user_path(@item.user_id) %><br>
  <% if @item.claimed %>
    <%= render 'claim' %>
    <% else %>
    <%= form_for @item do |f| %>
    <%= f.hidden_field(:claimed, value: true) %>
    <%= f.hidden_field(:claimer_id, value: current_user.id) %>
    <%= submit_tag "Claim Item" %><br>
    <% end %>
  <% end %>
<% end %>

<%= "#{@item.claimed}" %><br>
<%= "#{@item.claimer_id}" %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BEWDFinal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Welcome to Make My Day!</h1>

<% if user_signed_in? %>
	<%= "Hello, #{current_user.first_name}" %>
	<br>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <%= link_to "Edit User Profile", edit_user_registration_path %>
  <%= render 'registrations/search' %>
   	<% if @users %>
   		<%= render 'registrations/search_results' %>
   	<% end %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Login", new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Make My Day!</h1>

<h2>  Make My Day! is an app designed to make it easy to give, and receive, just the right gift to make someone's day brighter! Perfect for Christmas, Birthdays, Weddings, or any day of the year.  Not a member?  Signup Below and make someone's day today!</h2>